spring:
  application:
    name: realtime-service
  kafka:
    streams:
      bootstrap-servers: localhost:9092
      application-id: realtime-service


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true


server:
  port: 8087


realtime:
  kafka:
    topic:
      user:
        session: topic.user.session