spring:
  application:
    name: realtime-service
  kafka:
    streams:
      bootstrap-servers: localhost:9092
      application-id: realtime-service
      default:
        key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        value-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  data:
    redis:
      host: localhost
      port: 6379
  profiles:
    include: rabbitmq


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true


server:
  port: 8087

logging:
  level:
    com.chat.realtime_service: debug

realtime:
  kafka:
    topic:
      message:
        new: topic.message.new
        read: topic.message.read
        delivered: topic.message.delivered
        typing: topic.message.typing
        delete: topic.message.deleted
      websocket:
        message: topic.websocket.message
        user:
          session: topic.websocket.user.session

