spring:
  application:
    name: realtime-service
  kafka:
    streams:
      bootstrap-servers: localhost:9092
      application-id: realtime-service
      default:
        key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        value-serde: org.apache.kafka.common.serialization.Serdes$StringSerde


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true


server:
  port: 8087

logging:
  level:
    com.chat.realtime_service: debug

realtime:
  kafka:
    topic:
      user:
        session: topic.user.session